### ISSUE TITLE
Add some content to the README.md file

### ISSUE THREAD

**Issue by GangliTan** [DigitalCausalityLab/demo_repo#7]

**Comment by PhilippBach** [comment]
# Markdown format examples

*Hallo* 

**Hallo** 🥇 ![](https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Elephant_Diversity.jpg/1024px-Elephant_Diversity.jpg)

`code()` 

```
some code

```

@GangliTan 

#3 

- [ ] A
- [ ] B
- [ ] C
